### ISSUE TITLE
SVG Export

### ISSUE THREAD

**Issue by Wuerstl0815** [cuttingtemplates/community#81]
When producing a custom cutting template (i.e. simplex slat) the SVG Export doesn't work resulting in a 2.3KB invalid SVG File.
However, exporting the default as SVG works. Seems the same with other templates (e.g. Hexagon)

**Comment by NicoKNL** [comment]
Hello @Wuerstl0815 ,

Please try again. I restarted the server.

**Comment by Wuerstl0815** [comment]
works. thx! supererb job.
